# Generated by Django 6.0.6 on 2026-06-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1024)),
                ('goal_set_date', models.DateField()),
                ('set_to_complete', models.DateField()),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
