# Generated by Django 6.0.6 on 2026-06-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_complete',
            new_name='is_completed',
        ),
    ]
