# Generated by Django 6.0.6 on 2026-06-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_todo_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_of',
            new_name='owner',
        ),
    ]
