# Generated by Django 6.0.6 on 2026-06-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_todo_of_todo_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='owner',
            new_name='todo_of',
        ),
    ]
