# Generated by Django 6.0.6 on 2026-06-17 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_todo_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(help_text='Detailed description of the task (max 1024 characters)', max_length=1024),
        ),
        migrations.AlterField(
            model_name='todo',
            name='goal_set_date',
            field=models.DateField(help_text='Date when the task was created (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether the task has been completed or not'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='set_to_complete',
            field=models.DateField(help_text='Deadline for the task (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(help_text='Title of the task (max 50 characters)', max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_of',
            field=models.ForeignKey(help_text='User who created the task', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
