# Generated by Django 6.0.6 on 2026-06-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_todo_description_alter_todo_goal_set_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[(0, 'In Progress'), (1, 'To Do'), (2, 'Done')], default=1, help_text='Status of the task', max_length=20),
        ),
    ]
