# Generated by Django 6.0.6 on 2026-06-17 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the task (max 50 characters)', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the task (max 1024 characters)', max_length=1024)),
                ('goal_set_date', models.DateField(help_text='Date when the task was created (YYYY-MM-DD)')),
                ('set_to_complete', models.DateField(help_text='Deadline for the task (YYYY-MM-DD)')),
                ('status', models.CharField(choices=[(0, 'In Progress'), (1, 'To Do'), (2, 'Done')], default=1, help_text='Status of the task', max_length=20)),
                ('user', models.ForeignKey(help_text='User who created the task', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
