# Generated by Django 6.0.6 on 2026-07-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low'), (3, 'Zero')], default=3, help_text='Priority of the task', max_length=20),
        ),
    ]
