# Generated by Django 6.0.6 on 2026-07-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low'), (3, 'Zero')], default=3, help_text='Priority of the task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'To Do'), (2, 'Done')], default=1, help_text='Status of the task'),
        ),
    ]
