# Generated by Django 6.0.6 on 2026-08-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('ZERO', 'Zero')], default='ZERO', help_text='Priority of the task', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('TODO', 'To Do'), ('DONE', 'Done')], default='TODO', help_text='Status of the task', max_length=20),
        ),
    ]
