# Generated by Django 6.0.6 on 2026-08-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the task (max 1024 characters)', max_length=1024),
        ),
    ]
