# Generated by Django 6.0.6 on 2026-07-30 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='color',
            field=models.CharField(blank=True, default='#FFFFFF', help_text='Display color of the board in hex format (e.g. #FF0000)', max_length=7),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the board (max 2048 characters)', max_length=2048),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(help_text='Title of the board (max 100 characters)', max_length=100),
        ),
        migrations.AlterField(
            model_name='board',
            name='user',
            field=models.ForeignKey(help_text='User who created the board', on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
