# Generated by Django 6.0.6 on 2026-08-27 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_color_alter_board_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug of the board (max 100 characters)', max_length=100),
        ),
        migrations.CreateModel(
            name='BoardSlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_slugs', to='board.board')),
            ],
            options={
                'unique_together': {('board', 'slug')},
            },
        ),
    ]
