# Generated by Django 6.0.6 on 2026-08-27 08:30

from django.db import migrations

def backfill_slugs(apps, schema_editor):
    Board = apps.get_model('board', 'Board')
    from core.utils.slugs import generate_unique_slug
    for board in Board.objects.filter(slug=''):
        board.slug = generate_unique_slug(Board, board.title, board.user)
        board.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_slug_boardslughistory'),
    ]

    operations = [migrations.RunPython(backfill_slugs, migrations.RunPython.noop)]
