# Generated by Django 6.0.6 on 2026-08-27 08:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_backfill_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('user', 'slug')},
        ),
    ]
