/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates a new user account. No authentication required.
         */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Returns a token for the given username and password.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/about/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns the profile of the currently authenticated user.
         */
        get: operations["auth_about_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Invalidates the current token.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change password
         * @description Changes the password of the currently authenticated user.
         */
        post: operations["auth_change_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all boards
         * @description Returns all boards.
         */
        get: operations["boards_list"];
        put?: never;
        /**
         * Create a new board
         * @description Creates a new board. The author is automatically set to the logged in user.
         */
        post: operations["boards_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/archive-all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive multiple boards
         * @description Archives all boards or a subset by ids. If ids is empty or not provided, archives all boards.
         */
        post: operations["boards_archive_all_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/restore-all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore multiple boards
         * @description Restores all archived boards or a subset by ids. Pass `?restore_tasks=true` to restore tasks too.
         */
        post: operations["boards_restore_all_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a board
         * @description Returns the details of a specific board by its ID, including its tasks.
         */
        get: operations["boards_retrieve"];
        /**
         * Update a board
         * @description Fully updates a board. Only the author can update it.
         */
        put: operations["boards_update"];
        post?: never;
        /**
         * Delete a board
         * @description Deletes a board. Only the author can delete it.
         */
        delete: operations["boards_destroy"];
        options?: never;
        head?: never;
        /**
         * Partially update a board
         * @description Partially updates a board. Only the author can update it.
         */
        patch: operations["boards_partial_update"];
        trace?: never;
    };
    "/boards/{slug}/archive/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive a board
         * @description Archives a board and all its tasks. Only the author can archive it.
         */
        post: operations["boards_archive_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{slug}/restore/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a board
         * @description Restores an archived board. Pass `?restore_tasks=true` to restore its tasks too.
         */
        post: operations["boards_restore_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/delete-all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete multiple boards
         * @description Permanently deletes archived boards, or a subset by ids. If ids is empty or not provided, deletes all archived boards.
         */
        post: operations["boards_delete_all_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all tasks
         * @description Returns all tasks ordered by completion status, deadline and creation date.
         */
        get: operations["tasks_list"];
        put?: never;
        /**
         * Create a new task
         * @description Creates a new task. The author is automatically set to the logged in user.
         */
        post: operations["tasks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a task
         * @description Returns the details of a specific task by its ID.
         */
        get: operations["tasks_retrieve"];
        /**
         * Update a task
         * @description Fully updates a task. Only the author can update it.
         */
        put: operations["tasks_update"];
        post?: never;
        /**
         * Delete a task
         * @description Deletes a task. Only the author can delete it.
         */
        delete: operations["tasks_destroy"];
        options?: never;
        head?: never;
        /**
         * Partially update a task
         * @description Partially updates a task. Only the author can update it.
         */
        patch: operations["tasks_partial_update"];
        trace?: never;
    };
    "/tasks/archive-all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive multiple tasks
         * @description Archives all tasks or a subset by ids. If ids is empty or not provided, archives all tasks.
         */
        post: operations["tasks_archive_all_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/restore-all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore multiple tasks
         * @description Restores all archived tasks or a subset by ids. If ids is empty or not provided, restores all tasks.
         */
        post: operations["tasks_restore_all_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/archive/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive a task
         * @description Archives a task. Only the author can archive it.
         */
        post: operations["tasks_archive_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/restore/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a task
         * @description Restores an archived task. Only the author can restore it.
         */
        post: operations["tasks_restore_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/move/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move tasks to a board
         * @description Moves a list of tasks to a board. Pass `null` as board to remove tasks from their board.
         */
        post: operations["tasks_move_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/delete-all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete multiple tasks
         * @description Permanently deletes archived tasks, or a subset by ids. If ids is empty or not provided, deletes all archived tasks.
         */
        post: operations["tasks_delete_all_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Serializer for creating and updating boards.
         *
         *     `user` and `is_archived` are excluded because they are set server-side
         *     (user is derived from the request; archival is handled via dedicated endpoints).
         */
        Board: {
            readonly id: number;
            readonly is_archived: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly slug: string;
            /** @description Title of the board (max 100 characters) */
            title: string;
            /** @description Detailed description of the board (max 2048 characters) */
            description?: string;
            /** @description Display color of the board in hex format (e.g. #FF0000) */
            color?: string;
        };
        /** @description Read-only serializer that extends BoardSerializer with the board's active tasks. */
        BoardDetail: {
            readonly id: number;
            readonly tasks: components["schemas"]["Task"][];
            readonly is_archived: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly slug: string;
            /** @description Title of the board (max 100 characters) */
            title: string;
            /** @description Detailed description of the board (max 2048 characters) */
            description?: string;
            /** @description Display color of the board in hex format (e.g. #FF0000) */
            color?: string;
        };
        /**
         * @description Serializer for bulk operations that accept an optional list of integer IDs.
         *
         *     When `ids` is omitted or empty the corresponding service function is
         *     expected to apply the operation to all eligible objects owned by the user.
         */
        BulkIds: {
            /** @description List of ids to process. If empty or omitted, applies to all. */
            ids?: number[];
        };
        /**
         * @description Serializer for the change-password flow.
         *
         *     Does not extend ModelSerializer because it operates on request data only
         *     and never directly reads from or writes to a model instance.
         */
        ChangePassword: {
            /** @description Current password */
            old_password: string;
            /** @description New password */
            new_password: string;
            /** @description Repeat the new password to confirm */
            confirm_new_password: string;
        };
        /** @description Read-only serializer that exposes basic profile information for the current user. */
        Info: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            readonly username: string;
            /**
             * Email address
             * Format: email
             */
            readonly email: string;
        };
        /** @description Request payload for the login endpoint. */
        LoginRequest: {
            username: string;
            password: string;
        };
        PaginatedBoardList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Board"][];
        };
        PaginatedTaskList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Task"][];
        };
        /**
         * @description Serializer for creating and updating boards.
         *
         *     `user` and `is_archived` are excluded because they are set server-side
         *     (user is derived from the request; archival is handled via dedicated endpoints).
         */
        PatchedBoard: {
            readonly id?: number;
            readonly is_archived?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            readonly slug?: string;
            /** @description Title of the board (max 100 characters) */
            title?: string;
            /** @description Detailed description of the board (max 2048 characters) */
            description?: string;
            /** @description Display color of the board in hex format (e.g. #FF0000) */
            color?: string;
        };
        /**
         * @description Serializer for creating and updating tasks.
         *
         *     `user` and `is_archived` are excluded because they are managed server-side.
         *     The `board` field accepts a PK and validates that the board belongs to the
         *     requesting user, preventing cross-user board assignment.
         */
        PatchedTask: {
            readonly id?: number;
            readonly board_slug?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            /** @description Title of the task (max 50 characters) */
            title?: string;
            /** @description Detailed description of the task (max 1024 characters) */
            description?: string;
            /**
             * Format: date
             * @description Date when the task was created (YYYY-MM-DD)
             */
            goal_set_date?: string;
            /**
             * Format: date
             * @description Deadline for the task (YYYY-MM-DD)
             */
            set_to_complete?: string;
            /**
             * @description Status of the task
             *
             *     * `IN_PROGRESS` - In Progress
             *     * `TODO` - To Do
             *     * `DONE` - Done
             */
            status?: components["schemas"]["StatusEnum"];
            /**
             * @description Priority of the task
             *
             *     * `HIGH` - High
             *     * `MEDIUM` - Medium
             *     * `LOW` - Low
             *     * `ZERO` - Zero
             */
            priority?: components["schemas"]["PriorityEnum"];
            board?: number | null;
        };
        /**
         * @description * `HIGH` - High
         *     * `MEDIUM` - Medium
         *     * `LOW` - Low
         *     * `ZERO` - Zero
         * @enum {string}
         */
        PriorityEnum: "HIGH" | "MEDIUM" | "LOW" | "ZERO";
        /**
         * @description Serializer for creating a new user account.
         *
         *     `confirm_password` is a write-only field used only for client-side
         *     confirmation; it is stripped from validated data before the user is created.
         */
        Register: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Format: email */
            email: string;
            /** @description Password for the new account */
            password: string;
            /** @description Repeat the password to confirm */
            confirm_password: string;
        };
        /**
         * @description Generic response containing a human-readable message, used for
         *     action endpoints that don't return a resource (e.g. archive, restore).
         */
        SimpleMessageResponse: {
            detail: string;
        };
        /**
         * @description * `IN_PROGRESS` - In Progress
         *     * `TODO` - To Do
         *     * `DONE` - Done
         * @enum {string}
         */
        StatusEnum: "IN_PROGRESS" | "TODO" | "DONE";
        /**
         * @description Serializer for creating and updating tasks.
         *
         *     `user` and `is_archived` are excluded because they are managed server-side.
         *     The `board` field accepts a PK and validates that the board belongs to the
         *     requesting user, preventing cross-user board assignment.
         */
        Task: {
            readonly id: number;
            readonly board_slug: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** @description Title of the task (max 50 characters) */
            title: string;
            /** @description Detailed description of the task (max 1024 characters) */
            description?: string;
            /**
             * Format: date
             * @description Date when the task was created (YYYY-MM-DD)
             */
            goal_set_date: string;
            /**
             * Format: date
             * @description Deadline for the task (YYYY-MM-DD)
             */
            set_to_complete: string;
            /**
             * @description Status of the task
             *
             *     * `IN_PROGRESS` - In Progress
             *     * `TODO` - To Do
             *     * `DONE` - Done
             */
            status?: components["schemas"]["StatusEnum"];
            /**
             * @description Priority of the task
             *
             *     * `HIGH` - High
             *     * `MEDIUM` - Medium
             *     * `LOW` - Low
             *     * `ZERO` - Zero
             */
            priority?: components["schemas"]["PriorityEnum"];
            board?: number | null;
        };
        /**
         * @description Serializer for moving a batch of tasks to a different board (or no board).
         *
         *     `ids` is required and must be non-empty; `board` accepts a PK or null —
         *     passing null detaches the tasks from their current board.
         */
        TaskMove: {
            ids: number[];
            board: number | null;
        };
        /** @description Response returned after a successful login, containing the auth token. */
        TokenResponse: {
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            /** @description User created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Info"];
                };
            };
            /** @description Bad request — invalid data or passwords do not match. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many requests — rate limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Token returned successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid credentials. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many requests — rate limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_about_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Info"];
                };
            };
            /** @description Authentication credentials were not provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Authentication credentials were not provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_change_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePassword"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangePassword"];
                "multipart/form-data": components["schemas"]["ChangePassword"];
            };
        };
        responses: {
            /** @description Password changed successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Bad request — invalid data or wrong password. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication credentials were not provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    boards_list: {
        parameters: {
            query?: {
                /** @description Pass true to return archived boards instead of active ones. */
                is_archived?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBoardList"];
                };
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    boards_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Board"];
                "application/x-www-form-urlencoded": components["schemas"]["Board"];
                "multipart/form-data": components["schemas"]["Board"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            /** @description Bad request — invalid data. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    boards_archive_all_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BulkIds"];
                "application/x-www-form-urlencoded": components["schemas"]["BulkIds"];
                "multipart/form-data": components["schemas"]["BulkIds"];
            };
        };
        responses: {
            /** @description Boards archived successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Bad request — invalid data. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    boards_restore_all_create: {
        parameters: {
            query?: {
                /** @description Pass true to restore all tasks associated with the boards. */
                restore_tasks?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BulkIds"];
                "application/x-www-form-urlencoded": components["schemas"]["BulkIds"];
                "multipart/form-data": components["schemas"]["BulkIds"];
            };
        };
        responses: {
            /** @description Boards restored successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Bad request — invalid data. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    boards_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardDetail"];
                };
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Board not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    boards_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Board"];
                "application/x-www-form-urlencoded": components["schemas"]["Board"];
                "multipart/form-data": components["schemas"]["Board"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            /** @description Bad request — invalid data, or board is archived. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Board not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    boards_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Board deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request — board must be archived before deletion. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Board not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    boards_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBoard"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBoard"];
                "multipart/form-data": components["schemas"]["PatchedBoard"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            /** @description Bad request — invalid data, or board is archived. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Board not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    boards_archive_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Board archived successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Board not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    boards_restore_create: {
        parameters: {
            query?: {
                /** @description Pass true to restore all tasks associated with the board. */
                restore_tasks?: boolean;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Board restored successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Board not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    boards_delete_all_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BulkIds"];
                "application/x-www-form-urlencoded": components["schemas"]["BulkIds"];
                "multipart/form-data": components["schemas"]["BulkIds"];
            };
        };
        responses: {
            /** @description Boards deleted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Bad request — invalid data. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tasks_list: {
        parameters: {
            query?: {
                board?: number;
                /** @description Pass true to return archived tasks instead of active ones. */
                is_archived?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /**
                 * @description Priority of the task
                 *
                 *     * `HIGH` - High
                 *     * `MEDIUM` - Medium
                 *     * `LOW` - Low
                 *     * `ZERO` - Zero
                 */
                priority?: "HIGH" | "LOW" | "MEDIUM" | "ZERO";
                /** @description A search term. */
                search?: string;
                /**
                 * @description Status of the task
                 *
                 *     * `IN_PROGRESS` - In Progress
                 *     * `TODO` - To Do
                 *     * `DONE` - Done
                 */
                status?: "DONE" | "IN_PROGRESS" | "TODO";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTaskList"];
                };
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tasks_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Task"];
                "application/x-www-form-urlencoded": components["schemas"]["Task"];
                "multipart/form-data": components["schemas"]["Task"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Bad request — invalid data. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tasks_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tasks_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Task"];
                "application/x-www-form-urlencoded": components["schemas"]["Task"];
                "multipart/form-data": components["schemas"]["Task"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Bad request — invalid data, or task is archived. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tasks_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request — task must be archived before deletion. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tasks_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTask"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTask"];
                "multipart/form-data": components["schemas"]["PatchedTask"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Bad request — invalid data, or task is archived. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tasks_archive_all_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BulkIds"];
                "application/x-www-form-urlencoded": components["schemas"]["BulkIds"];
                "multipart/form-data": components["schemas"]["BulkIds"];
            };
        };
        responses: {
            /** @description Tasks archived successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Bad request — invalid data. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tasks_restore_all_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BulkIds"];
                "application/x-www-form-urlencoded": components["schemas"]["BulkIds"];
                "multipart/form-data": components["schemas"]["BulkIds"];
            };
        };
        responses: {
            /** @description Tasks restored successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Bad request — invalid data. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tasks_archive_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task archived successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tasks_restore_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task restored successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tasks_move_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskMove"];
                "application/x-www-form-urlencoded": components["schemas"]["TaskMove"];
                "multipart/form-data": components["schemas"]["TaskMove"];
            };
        };
        responses: {
            /** @description Tasks moved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Bad request — invalid data. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tasks_delete_all_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BulkIds"];
                "application/x-www-form-urlencoded": components["schemas"]["BulkIds"];
                "multipart/form-data": components["schemas"]["BulkIds"];
            };
        };
        responses: {
            /** @description Tasks deleted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Bad request — invalid data. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized or not authenticated. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
